Group 3 Members:

Nana Ama Annor <br>
Solomon Asamoah <br>
Dorothy Assan <br>
Mawuko Abla Diaba <br>
Anita Yeboah <br>

ASSIGNMENT

1.Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10. Expected Output: [[ 2 3 4] [ 5 6 7] [ 8 9 10]]

Write a NumPy program to create a null vector of size 10 and update the sixth value to 11. [ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] Update sixth value to 11 [ 0. 0. 0. 0. 0. 0. 11. 0. 0. 0.]

Write a NumPy program to create an array with values ranging from 12 to 38. Expected Output: [12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]

Write a NumPy program to reverse an array (the first element becomes the last). Original array: [12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37] Reverse array: [37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12]

Write a NumPy program to convert an array to a floating type. Sample output: Original array [1, 2, 3, 4] Array converted to a float type: [ 1. 2. 3. 4.]

Write a NumPy program to create a 2D array with 1 on the border and 0 inside. Expected Output: Original array: [[ 1. 1. 1. 1. 1.] ................... [ 1. 1. 1. 1. 1.]]

Write a NumPy program to find the number of elements in an array. It also finds the length of one array element in bytes and the total bytes consumed by the elements. Expected Output: Size of the array: 3 Length of one array element in bytes: 8 Total bytes consumed by the elements of the array: 24

In [14]:
import numpy as np
array1 = np.arange(2,11)
array1 = array1.reshape((3,3))


array1

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [22]:
array2 = np.zeros(10)
array2

array2[5] = 11
array2

array([ 0.,  0.,  0.,  0.,  0., 11.,  0.,  0.,  0.,  0.])

In [23]:
array3 = np.arange(12,39)
array3

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37, 38])

In [26]:
array4 = np.sort(array3)[::-1]
array4

array([38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22,
       21, 20, 19, 18, 17, 16, 15, 14, 13, 12])

In [28]:
array5 = np.arange(1,5)

float_array5 = array5.astype(float)
float_array5

array([1., 2., 3., 4.])

In [35]:
#Creating a 5x5 array of zeros
array_2d = np.zeros((5, 5))
array_2d


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [36]:
# Changing all entries in the first row to 1 
array_2d [0,:] = 1
array_2d

array([[1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [37]:
# Changing all entries in the last row to 1 
array_2d [4,:] = 1
array_2d

array([[1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.]])

In [38]:
# Changing all entries in the first column to 1 
array_2d [:,0] = 1
array_2d

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.]])

In [39]:
# Changing all entries in the last column to 1 
array_2d [:, 4] = 1
array_2d

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [40]:
array6 = np.arange(1,11)
array6

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
array_size = np.size(array6)
array_size

10

In [44]:
element_memory_size = array6.itemsize
element_memory_size 

4

In [48]:
total_memory_size = element_memory_size * array_size
total_memory_size

40

In [50]:
print ("Size of the array:",array_size )
print ("Length of one array element in bytes:",element_memory_size )
print ("Total bytes consumed by the elements of the array:",total_memory_size )

Size of the array: 10
Length of one array element in bytes: 4
Total bytes consumed by the elements of the array: 40
